<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <SelfContained>true</SelfContained>
    <ImplicitUsings>false</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <Platforms>x64</Platforms>
    <DebugSymbols>true</DebugSymbols>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <Description>Tries to convert ChatGPT HTML code to MarkDown</Description>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

</Project>
